order += "load"
#order += "cpu_temperature 0"
order += "cpu_usage"
order += "memory"
order += "disk /"
#order += "volume microphone"
order += "volume master"
order += "ethernet eth0"
#order += "wireless lo"
order += "wireless enp7s0"
order += "wireless wlp0s20f3"
order += "battery 0"
order += "time"

load {
	max_threshold = 15
	format = "WAIT: %1min"
}

#cpu_temperature 0 {
#	format = "CPU: %degrees °C"
#}

cpu_usage {
	max_threshold = 90
	degraded_threshold = 75
	format = "CPU: %usage"
}

memory {
	format = "RAM: %percentage_used (%used)"
	threshold_degraded = 25%
	threshold_critical = 10%
}

disk "/" {
	format = "DISK: %percentage_used (%used)"
}

#volume microphone {
#	device = "hw:0"
#	mixer = "Capture"
#	format = "♪ (Mic): %volume"
#	format_muted = "♪ (Mic): Muted"
#	mixer_idx = 0
#}

volume master {
	device = "default"
	mixer = "Master"
	mixer_idx = 0
	format = "♪ (%devicename): %volume"
	format_muted = "♪ (%devicename): M"
}

ethernet eth0 {
	format_up = "Eth: %(speed)"
	format_down = ""
}

wireless enp7s0 {
	format_down = ""
	format_up = "%essid @ %frequency (%bitrate)"
	format_bitrate = "%g %cb/s"
}

wireless wlp0s20f3 {
	format_down = "No Internet"
	format_up = "%essid @ %frequency (%bitrate)"
	format_bitrate = "%g %cb/s"
}

battery 0 {
	format = "BAT: %status %remaining"
	format_down = ""
}

time {

}
